@startuml 1/wallet-attestation-references-presentation
title Wallet and WSCDs references in attestations - presentation


!include <c4/C4_Context.puml>
!include <c4/C4_Container.puml>
!include <c4/C4_Component.puml>
!include <c4/C4_Dynamic.puml>
!include <c4/C4_Sequence.puml>
!include <office/Users/user.puml>
!include <office/Users/mobile_user.puml>

HIDE_STEREOTYPE()
autonumber "<b>[00] - "

Component(wallet, "Wallet")
Component(verifier, "Verifier")
Component(issuerWA, "Wallet attestation \n revocation registry", "accumulator")
Component(issuerWSCD, "WSCD revocation \n registry", "accumulator")


note over wallet
| <math>Attestation</math> | <math>[["claims1=digest_claims1, ... , "], [ "walletAttestationId=wallet_attestation_id"],  ["wscd=holder_secret_WSCD_reference "]]</math>|
| <math>Signature</math> | <math>signature_("issuer")</math> |
| <math>Disclosures</math> | <math>"disclosure_of_claims1 ... "</math>|
end note

== Attestation presentation ==
BiRel(wallet, verifier, "presentation process")
BiRel(wallet, issuerWA, "Get delta")
BiRel(wallet, issuerWSCD, "Get delta")
Rel(wallet, wallet, "Update accumulators states and witnesses with deltas")
Rel(wallet, wallet, "Generate values commitments")
Rel(wallet, wallet, "Generate //walletAttestationNonRevocationZKP//")
Rel(wallet, wallet, "Generate //WSCDNonRevocationZKP//")
Rel(wallet, wallet, "Generate presentation")

note over wallet
presentation =
| <math>Attestation</math> | <math>[["claims1=digest_claims1, ... ,"], ["walletAttestationId=<staticValue>"], ["wscd=<staticValue>"]]</math>|
| <math>Signature</math> | <math>signature_("issuer")</math> \n <math>"WalletAttestation : Commitment + UndisclosedZKP + NonRevocationZKP "</math> \n <math>"wscd : Commitment + UndisclosedZKP + NonRevocationZKP"</math> |
| <math>Disclosures</math> | <math>"disclosure_of_claims1 ... "</math>|
presentation signature = <math>signature_("holder")</math>
end note

Rel(wallet, verifier, "Share presentation")
BiRel(verifier, issuerWA, "Verify NonRevocationZKP(walletAttestationNonRevocationZKP)")
BiRel(verifier, issuerWSCD, "Verify NonRevocationZKP(WSCDNonRevocationZKP)")
Rel(verifier, verifier, "Verify presentation and extract claims")

@enduml